### ISSUE TITLE
[BUG] Winston throws error after fresh install

### ISSUE THREAD

**Issue by rzelazny** [sauravhiremath/fifa-api#40]
**Description**
A fresh installation of the project is unable to start. After the npm install and run start, the app crashes with the error:

TypeError: _winston.Logger is not a constructor

**To Reproduce**
1. Start with a fresh clone of the repo
2. npm install
3. npm run start
4. See error TypeError: _winston.Logger is not a constructor

**Expected behavior**
Ideally the app should start up without an error.

**Desktop**
 - OS: Windows 10
 - Browser Chrome

**Comment by sauravhiremath** [comment]
@rzelazny feel free to check out the PR if it throws any additional errors on your system. Should be gtg afaik
