### ISSUE TITLE
[BUG] Fix CORs issue

### ISSUE THREAD

**Issue by sauravhiremath** [sauravhiremath/fifa-api#5]
**Describe the bug**
Socket.io uses its own implementation of parsing origin when it comes to cors. Using `${host}:*` doesn't work with both 
 - When `host` is `http://localhost:3000`
 - When `host` is a URL with a domain name `fifa.sauravmh.me`

Fixes below don't work

Ref: 
https://github.com/socketio/socket.io/issues/2850
https://github.com/socketio/socket.io/issues/2294

**To Reproduce**
1. Open on `localhost:3000`
2. Open on your own domain or `fifa.sauravmh.me`
3. It ought to give cors error on one of them if not both

**Expected behavior**
No cors error on both using URLs and URLs with domains

**Screenshots**
![cors-error-on-chromium](https://user-images.githubusercontent.com/28642011/85907453-26abfa00-b82f-11ea-8d73-b7c709b34b6d.png)

**Comment by Muratcol** [comment]
Hey there, I'm having the same issue.

My API working fine but when I trying to connect Angular chat application with socket.io to express, sending same error. 

`app.use(cors())
app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", 'http://localhost:4200/'); 
    res.header("Access-Control-Allow-Credentials", true);
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
    res.header("Access-Control-Allow-Headers",
  'Origin,X-Requested-With,Content-Type,Accept,content-type,application/json,Authorization');
    next();
  });`

This header options or any other solutions didn't work.

**Comment by sauravhiremath** [comment]
Hey, @Muratcol is the app object attached the same `http.server` which is used for socketio?

Ideally, to handle cors for socketio and HTTP server, you can use the following solution:


```javascript
import express from 'express';
import http from 'http';
import socketio from 'socketio';

const app = express();
const server = new http.Server(app);

// This is setting cors for HTTP server
app.use(cors({ origin: 'http://localhost:4200', credentials: true }));

// This is setting cors for socketio server
const io = socketio.listen(server, {
  origins: ['http://localhost:4200']
});
```

**Comment by Muratcol** [comment]
Yes, app object attached `http://localhost:5000`

I solved my error today. I'm not sure what I did differently. But my error disappeared. And socket.io working properly. 
Actually, I was very angry. I erased everything and rewrote it. 😄 

Last version of my codes.

```
const app = express();
app.use(function(req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  res.setHeader('Access-Control-Allow-Methods', 'POST, GET, PATCH, DELETE, OPTIONS');
  next();
});
const port = normalizePort(process.env.PORT || '5000');
app.set('port', port);
const server = http.createServer(app);
const io = require('socket.io').listen(server);
```

**Comment by sauravhiremath** [comment]
That does seem to work. But it does have a security issue.

The `*` here allows access from any origin, acting as a wildcard. It is much safer to use ~whitelisted~ safelisted origins only.

```javascript
res.setHeader('Access-Control-Allow-Origin', '*');

//instead you may use something like
res.setHeader('Access-Control-Allow-Origin', 'http://localhost:4200');
```

**Comment by Muratcol** [comment]
You're right. I changed my header. It still works. Thank you very much. 

What about your problem? Is it still exist?

**Comment by sauravhiremath** [comment]
Yeah, it still exists :( Seems a problem specific to socket.io library (along with their tons of other issues). 

Socketio parses the `$host` passed in a weird WRONG way. This is how it works internally.

```javascript
/**
 * Server request verification function, that checks for allowed origins
 *
 * @param {http.IncomingMessage} req request
 * @param {Function} fn callback to be called with the result: `fn(err, success)`
 */

Server.prototype.checkRequest = function(req, fn) {
  var origin = req.headers.origin || req.headers.referer;

  // file:// URLs produce a null Origin which can't be authorized via echo-back
  if ('null' == origin || null == origin) origin = '*';

  if (!!origin && typeof(this._origins) == 'function') return this._origins(origin, fn);
  if (this._origins.indexOf('*:*') !== -1) return fn(null, true);
  if (origin) {
    try {
      var parts = url.parse(origin);
      var defaultPort = 'https:' == parts.protocol ? 443 : 80;
      parts.port = parts.port != null
        ? parts.port
        : defaultPort;
      var ok =
        ~this._origins.indexOf(parts.protocol + '//' + parts.hostname + ':' + parts.port) ||
        ~this._origins.indexOf(parts.hostname + ':' + parts.port) ||
        ~this._origins.indexOf(parts.hostname + ':*') ||
        ~this._origins.indexOf('*:' + parts.port);
      debug('origin %s is %svalid', origin, !!ok ? '' : 'not ');
      return fn(null, !!ok);
    } catch (ex) {
    }
  }
  fn(null, false);
};
```

It doesn't detect the PORT number correctly when passed along with domain name in a URL (Ex: `https://abcd.example.com`).
Here ideally it should detect PORT number is not present and add `443` to the end as attempted on the above code.

But, sadly it doesn't.

You have to add `443` to the URL manually when passing it in origin. But this isn't viable when you are using the same `host` variable to store `http://localhost:4000` as well as `abcd.example.com` (depending on dev or production env) unless you modify the URL again to match socket.io's pattern (which is a very hacky fix, not clean)

**Comment by sauravhiremath** [comment]
Thanks, @Muratcol for making me work on this issue and bringing it to end.

I've added my own parser, which filters the URLs the right way before passing it to socket.io (as they need it)

Fixed here https://github.com/sauravhiremath/fifa-api/pull/6/commits/a97b1b279c9f8376c71a3e242f8baa0b844ff6c0

**Comment by Muratcol** [comment]
😄  I'm very glad to hear this. Your solution is reasonable and useful.

It seems that one day I will have to use this kind of controller.

Thanks, @sauravhiremath  Nice to meet you.
