### ISSUE TITLE
[FEATURE] - Add dependabot

### ISSUE THREAD

**Issue by Akshayp02** [sauravhiremath/fifa-api#92]
To add Dependabot to a project, create a dependabot.yml file in project root. Configure it to check for updates in project's dependencies, and set up notifications for automated pull requests. Dependabot will then help keep dependencies up-to-date, enhancing project stability and security.

**Comment by sauravhiremath** [comment]
I already experimented with dependabot for this project, but decided to drop it. It's currently going through a major upgrade (release ETA not set yet)

So, we won't be adding dependabot for this yet
